# Site settings
title: Anthony Oliver Portfolio
description: The work and accolades of Anthony Oliver
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anthonymoliver.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
